### ISSUE TITLE
[FEATURE] Sitewide Layout Component/Header

### ISSUE THREAD

**Issue by dylanesque** [codeforboston/police-data-trust#103]
In the current design documents, there is no header on the page before the user signs up for or registers for an account. I'm suggesting the following change:

- The site header/nav-element seen in the Figma docs will appear on *all* pages, with the adjustment of the "Search" and "Profile" links won't be visible, or routable. 

This will give the site a more consistent look, and enable us to use a more conventional Layout component, that wraps everything else the site renders.

**Comment by acharliekelly** [comment]
How about two tabs, "About" and "Login"? Login would just be the current Login layout, but without the logo.

**Comment by dylanesque** [comment]
> How about two tabs, "About" and "Login"? Login would just be the current Login layout, but without the logo.

That could be worth considering, though I think the current header, minus the routes that shouldn't be active for unauthenticated users, works very well.
