### ISSUE TITLE
[FEATURE] Create map key

### ISSUE THREAD

**Issue by sashamaryl** [codeforboston/police-data-trust#112]
![image](https://user-images.githubusercontent.com/30247522/129097651-a6b48ed9-c316-49a3-aafd-3cc759a6e23f.png)

create a key for the map (see figma for design, use d3)

include:
- color gradient block scale
- symbol guide

should be able to accommodate other types of scales and additional data
should be reusable for other types of visualizations (not tied to map-type)

**Comment by edward-malouf** [comment]
Is this enough of a gradient? I think we might want to go darker by two additional steps.
