### ISSUE TITLE
[FEATURE] create Search Panel component

### ISSUE THREAD

**Issue by acharliekelly** [codeforboston/police-data-trust#131]
Search panel component, to appear on the side of the Dashboard page:

![search-panel](https://user-images.githubusercontent.com/46508773/131792082-7c45d8ba-35a8-49ef-90bb-72928e727d21.png)

**Requirements**
- Button to switch between Incident and Officer search
- Location (text) - both types of search
- Incident Type field (drop-down) - Incident only
- Date/Time (pop-up calendar input) - Incident only
- Officer name (text) - Officer only
- Badge number (text) - Officer only

**Comment by ascampos** [comment]
As discussed, we will change "Incident Type" to "Keywords"
