### ISSUE TITLE
[FEATURE] create Officer Record view

### ISSUE THREAD

**Issue by acharliekelly** [codeforboston/police-data-trust#136]
![officer-record](https://user-images.githubusercontent.com/46508773/131800133-d797f4d4-c0c8-462c-a334-f752bd86c2c7.png)

The current [FIGMA design](https://www.figma.com/file/TM86P6ePUar5g24pk4h6Du/NPDC-2?node-id=2260%3A4622) is available for reference, but it has not been finalized.

**Requirements**
Take the API data for an Officer Record and display it in a modal frame. Don't spend too much time on the presentation, because it's probably going to change.

Here are some fields that should be visible:
- Name
- Badge No.
- Rank/Status
- Department
- Demographic info
- Work history - list of departments
- Incident reports - incident table with links to Incident Record view - (#135)

**Comment by Logan-Dang** [comment]
Looking to start on this, but not sure where to start.

**Comment by Logan-Dang** [comment]
[] Add functionality to make it possible to get officer from search
[] Link to Fill Incident Record when it's functional
[] Polish Final Design
