### ISSUE TITLE
[FEATURE] Update User schema and auth form fields to match requirements

### ISSUE THREAD

**Issue by alexjball** [codeforboston/police-data-trust#155]
- Serialize the `role` field of User objects in our [schema](https://github.com/codeforboston/police-data-trust/blob/5b6fede1bc225b8d17389c04b687c7a061f76706/backend/schemas.py#L119). `role` is an enum, which pydantic can't serialize, so we currently exclude it. Ideally, we can use an enum type that pydantic supports.l
- Registration currently collects the user's phone number but it's not stored on the backend. Either add phone number to the `User` schema or remove it from the form. Need to clarify the requirement here.

**Comment by acharliekelly** [comment]
I think we need to collect the phone number, because the Password Recovery flow allows users to enter a phone number if they forgot their email address, so we'd need to store that somewhere.
