### ISSUE TITLE
[FEATURE] Set up secrets for deployment actions

### ISSUE THREAD

**Issue by alexjball** [codeforboston/police-data-trust#202]
We need to set these secrets in order to build and deploy production containers with github actions

https://github.com/alexjball/police-data-trust/blob/5fa3652c987e3f70cf95d6e01c2977d7a03ca3c0/.github/workflows/aws-ecs-deploy-frontend.yml#L73

AWS_ACCESS_KEY_ID 
AWS_SECRET_ACCESS_KEY 
AWS_ACCOUNT_ID

**Comment by DMalone87** [comment]
Closing.
