### ISSUE TITLE
[BUG] Fix header to be mobile responsive and match designs

### ISSUE THREAD

**Issue by srsexton94** [codeforboston/police-data-trust#231]
The header/nav component is not fully mobile responsive, with the tabs falling off the screen at various breakpoints. 

It also does not fully match the wireframes with element sizing and by missing the "DONATE" button (which should functionally be a link, the URL is still TBD we can use a placeholder for now)

Bug screenshots:
![Screen Shot 2022-02-08 at 8 20 59 PM](https://user-images.githubusercontent.com/50561643/153104883-0f7535ca-1a54-4cf5-ba3f-a682f67af41f.png)
![Screen Shot 2022-02-08 at 8 21 25 PM](https://user-images.githubusercontent.com/50561643/153104887-62006932-ad4e-49d8-954f-7d75103f8dc1.png)

### This ticket is to make sure that:
1. Desktop and Mobile views match the wireframes
2. All elements in the header, at all breakpoints between mobile and desktop, are visible, functional, and have generally reasonable proportions
3. All elements in wireframes are included in the header (ie add the Donate button)

Final check - zoom page into 400% and make sure all elements are visible & functional (accessibility requirement - WCAG 1.4.10) 
(Note: this should largely be handled by the mobile responsiveness - if this seems like it will significant complexity we can break it out into a separate ticket)

### Wireframes for intended design:
[Desktop Header](https://www.figma.com/file/TM86P6ePUar5g24pk4h6Du/NPDC--2?node-id=1373%3A2)
[Mobile Header Closed](https://www.figma.com/file/TM86P6ePUar5g24pk4h6Du/NPDC--2?node-id=1621%3A1683)
[Mobile Header Open](https://www.figma.com/file/TM86P6ePUar5g24pk4h6Du/NPDC--2?node-id=1744%3A2091)

### Out of Scope:
This ticket is not concerned with... 
1. the mobile responsiveness with any content below the header
2. the interaction design of the tabs/button (ie. you don't have to fix where these tabs are going if they're not correct/functional)

**Comment by azemetre** [comment]
Will include adding the `Donate` link in the mobile view as well.
