### ISSUE TITLE
scraped data --> to --> aws

### ISSUE THREAD

**Issue by sashamaryl** [codeforboston/police-data-trust#243]
run the scrapers and load the data into aws 

// @Jeff & @mikeyavorsky  please fill in the details from the convo in the meeting just now...

**Comment by mikeyavorsky** [comment]
We need to populate the database in the dev environment.

The scraper might be able to run locally with ENV variables pointing to AWS database.

**Comment by jigsawlabs-student** [comment]
Create an RDS database in AWS
