### ISSUE TITLE
[FEATURE] app.json

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/police-data-trust#25]
### Overview

The `app.json` is a Heroku deployment manifest file for apps that are not built via the container registry.

https://devcenter.heroku.com/articles/app-json-schema

### Requirements for issue:

- Create a valid `app.json`.
- Add one of those "one click deploy" buttons in the `README.md`.

The previous project I worked on is a good example of how to do all these things: https://github.com/codeforboston/flagging

For our project we would just want the Postgres add-on, and a SECRET_KEY I think for now.

**Comment by dwreeves** [comment]
This thing:

<img width="982" alt="image" src="https://user-images.githubusercontent.com/31971762/115473141-2be89400-a209-11eb-8a77-5d0a133e40ee.png">

It's simple to add to a `README.md`. This works for any arbitrary repo with a valid `app.json`.

```markdown
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy)
```

**Comment by DMalone87** [comment]
Closing as this approach is not compatible with a Docker/Heroku pairing.
