### ISSUE TITLE
[FEATURE] Fix up schema

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/police-data-trust#26]
### Overview

We have a schema document on Google Drive. We should make sure we implement it because right now we just have a flat table.

### Requirements for issue

- Look at existing data out there (see the about page in the docs for more), and get a good idea of what we want to do.
- Add to schema doc we currently have, validate it, critique it, etc. https://docs.google.com/document/d/1fcIQoyUuwTtM0Ik8U43B6qkCHTL8ttT7VsRCne9vyBs/edit#
- Implement the new schema.
- Come up with a list of questions about our attempt at a schema for other stakeholders.

**Comment by DMalone87** [comment]
Schema is currently being worked on in the Data Council Meetings ([minutes here](https://docs.google.com/document/d/1JT88M5S64z34GM8Z9w5Io-W6vUUPKznlw79t6-gyO1w/edit?usp=sharing)).

Tentative schema can be found in the [Schema Development](https://drive.google.com/drive/folders/1qdEDnLPwKvvM0GJCG5kCZ29vujerfPsK?usp=sharing) workspace as [NPDC.yml](https://drive.google.com/file/d/1gY3uDTP4-OyLdWbrZgqWS6mNc26AArLG/view?usp=sharing).
