### ISSUE TITLE
[FEATURE Clarify README's regarding frontend or backend instructions

### ISSUE THREAD

**Issue by ErikaVasNormandy** [codeforboston/police-data-trust#262]
**Is your feature request related to a problem? Please describe.**
Currently, there are two README's, one focused on the backend, and the other focused on the frontend

**Describe the solution you'd like**
Mention at the top of the initial README that first time users encounter, where to go if they would like to run the frontend or backend.

**Additional context**
This was based on just a cursory glance on the starting out instructions, assuming that first time users will be unfamiliar with the project structure and to anticipate any confusion/troubleshooting that may arise

**Comment by caseydulong** [comment]
I'm going to take a look at this tonight.

**Comment by caseydulong** [comment]
After chatting with Erika and Darrell, I made some very small changes to the root README, and the frontend README.  Made sure the two sets of instructions link to each other to help newcomers find their way through the setup more easily.  I'll make a PR for the small changes now.
