### ISSUE TITLE
[BUG] /whoami endpoint failing

### ISSUE THREAD

**Issue by JMStudiosJoe** [codeforboston/police-data-trust#265]
**Describe the bug**
when trying to login the web app frontend checks the `/whoami` endpoint and that is failing for all pages

**To Reproduce**
1. Go to /login
2. attempt to load main page
3. should see error in the dev console or the terminal where running from

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexjball** [comment]
This works locally. At some point we renamed the /test endpoint to /whoami. The frontend was deployed with this new path, but the backend wasn't. So login fails on the dev deployment as it tries to access the missing route. Redeploying the dev api should fix the issue.

**Comment by rosyntow** [comment]
I was not able to reproduce the issue locally. Here is the screenshot
![npdc_login](https://user-images.githubusercontent.com/4240493/235048702-8aa318a7-3cab-46e3-91a9-483921ecb54b.jpg)

**Comment by mikeyavorsky** [comment]
To reproduce: in Safari, Develop > Empty Caches. Load the page, log in with good credentials and you will see an error message. Click login again, and it will succeed.
