### ISSUE TITLE
[BUG] Phone number field at Login should not require spaces

### ISSUE THREAD

**Issue by DMalone87** [codeforboston/police-data-trust#272]
**Describe the bug**
When creating an account, the form will throw an error unless you use spaces in the phone number. Ex: "555 xxx xxxx". One should be able to use dashes or periods or the phone number should automatically add the desired formatting when you're typing out the number.

**To Reproduce**
1. Go to 'dev.nationalpolicedata.org'
2. Click on 'Join Us'
3. Enter the required information into the form and click submit.

**Expected behavior**
When you are entering a phone number for the account creation process, it should either not be as strict or it should handle the formatting automatically.

**Screenshots**
![Screen Shot 2023-04-04 at 9 22 16 PM](https://user-images.githubusercontent.com/8228564/229960508-e4f46b7a-81a2-4eb0-b9d4-18105730dd5a.png)

**Comment by rosyntow** [comment]
I have created a [pull request] (https://github.com/codeforboston/police-data-trust/pull/273) for this ticket.
Modified the regular expression to cover these variations of the formats of phone numbers below:
 +123456789012
  1234567890
  (123) 456-7890
 123-456-7890
