### ISSUE TITLE
[BUG] Invalid form values don't prevent account creation

### ISSUE THREAD

**Issue by mikeyavorsky** [codeforboston/police-data-trust#275]
**Describe the bug**
When using the signup form, validation errors don't prevent account creation.

**To Reproduce**
1. Go to '/register'
2. Fill in a last name with an _, or an invalid phone number
3. An error should appear, and you will remain on the same screen
4. Go to '/login'
5. Try to login with the credentials used during the signup step

**Expected behavior**
If you encounter an error in the signup form, the account should not be created until the user fixes the issues.

**Screenshots**
<img width="2672" alt="Screen Shot 2023-05-09 at 9 23 58 PM" src="https://github.com/codeforboston/police-data-trust/assets/1855512/97bf441b-ad55-4573-8e22-903d3c1e84f4">

**Comment by mikeyavorsky** [comment]
Brian S. is going to take a look.

**Comment by rosyntow** [comment]
Followed steps. Could not reproduce issue

**Comment by mikeyavorsky** [comment]
Can't reproduce on https://dev.nationalpolicedata.org/ either, closing.
