### ISSUE TITLE
[BUG] Expired session should redirect to Login Page

### ISSUE THREAD

**Issue by DMalone87** [codeforboston/police-data-trust#293]
**Describe the bug**
When an API call is made that requires an authenticated user, the app currently fails without giving a clear reason to the user. In cases where the API returns an "Unauthorized" response, we should redirect the user to the login page.

**To Reproduce**
1. Log in to the application
2. Visit the search page
3. Allow the session token to expire, but stay on the search page
4. Attempt to make a search.

-- OR --
1. Navigate to the search page by using the URL without being logged in
2. Attempt to make a search

**Expected behavior**
When a user attempts to perform a task that requires them to be logged in, they should be taken to a login page.

**Screenshots**
![Screenshot 2023-08-06 at 1 16 30 AM (2)](https://github.com/codeforboston/police-data-trust/assets/8228564/fe6ebb32-b00c-4bf3-8f9b-79268a850be6)

**Additional Context**
Server returns a 422 status code in this case.
Response: `{"msg":"Signature verification failed"}`

**Comment by mikeyavorsky** [comment]
Anirudh is investigating this issue.
