### ISSUE TITLE
[FEATURE] Switch backend container to Graviton

### ISSUE THREAD

**Issue by zganger** [codeforboston/police-data-trust#383]
Graviton performs better and consumes less power and therefore costs 20% less than intel systems. We can adopt it for our backend containers.

Steps:

- add `--platform=linux/arm64` to docker builds in GitHub actions
    - https://github.com/kciter/aws-ecr-action - using the `extra_build_args` option
- update the ECR task role to use graviton/ linux ARM hosts to run the jobs
- merge and deploy

**Comment by zganger** [comment]
note: we could consider on Frontend containers as well but I haven't tested. That could be a separate issue if we like this.

**Comment by mikeyavorsky** [comment]
Doesn't work without arm64 Github Actions runner (currently in private beta?)

**Comment by zganger** [comment]
This has been resolved by using qemu in actions to build. We could probably speed it up a little bit when the arm64 actions runner comes out, but until then this can be closed as done.
