### ISSUE TITLE
[FEATURE]register basic user

### ISSUE THREAD

**Issue by JMStudiosJoe** [codeforboston/police-data-trust#47]
![image](https://user-images.githubusercontent.com/4028643/122139019-d7bef200-cdfc-11eb-993f-2a7db73c571c.png)

**Comment by acharliekelly** [comment]
On the Index Requirements, item 4, it mentions allowing Facebook logins (ie OAuth). Are we doing that, or is it a stretch requirement?

**Comment by acharliekelly** [comment]
replaced with newer design spec by #58 , though basic requirements are still the same
