### ISSUE TITLE
[FEATURE] create login page

### ISSUE THREAD

**Issue by JMStudiosJoe** [codeforboston/police-data-trust#48]
**Initial**
![image](https://user-images.githubusercontent.com/4028643/122139095-063ccd00-cdfd-11eb-9a23-71c02dd9dec8.png)

**Validation**
![login-validation](https://user-images.githubusercontent.com/46508773/122807360-7d5ce000-d299-11eb-8d41-0bf790470d54.png)

**Comment by acharliekelly** [comment]
### Updated Design Spec

**Initial**
![login](https://user-images.githubusercontent.com/46508773/122445500-9dc22d00-cf6f-11eb-92f7-8aa4d2477248.png)

**Validation**
![login-validation](https://user-images.githubusercontent.com/46508773/122445550-a87cc200-cf6f-11eb-96c1-a9b0cdc6f4d0.png)

**Comment by Devtinator** [comment]
I would like to work on this too.

**Comment by Abhispy007** [comment]
This is far from being done, but I followed a tutorial, and got this far. Any thoughts/next steps? 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/45133270/123019193-03624f00-d39e-11eb-809c-f8551302d648.png">

**Comment by JMStudiosJoe** [comment]
@Devtinator have you started any changes? @Abhispy007 are you able to self assign this if you are taking this on? Yes, please make a branch and we can review the changes you have. Then we can make it look like the designs as well and then merge.

**Comment by Devtinator** [comment]
So sorry, I haven't been able to working on it yet, I'm having issues starting the app locally on my PC, still trying to figure that out.

**Comment by Abhispy007** [comment]
@JMStudiosJoe created a branch called create-login-page. I also created a draft pull request as well. I'm not sure if I was supposed to do that, feel free to delete the pull request if it's not needed for now.
