### ISSUE TITLE
[FEATURE] create Registration response page

### ISSUE THREAD

**Issue by acharliekelly** [codeforboston/police-data-trust#49]
Response screen for after user creates a new profile. Can use one page for all possible outcomes - only the message will change, depending on type of user and response (Viewer or Passport, success or failure).

**Success**
![profile-response](https://user-images.githubusercontent.com/46508773/122792367-1d117280-d288-11eb-8740-186728526420.png)

**Error**
![profile-response-error](https://user-images.githubusercontent.com/46508773/122792896-927d4300-d288-11eb-8072-62fcb68b2a90.png)

**Comment by acharliekelly** [comment]
er, I don't seem to be able to add labels, but this should be labeled as frontend and good first issue

**Comment by acharliekelly** [comment]
**Updated design, same requirements**
![profile-response](https://user-images.githubusercontent.com/46508773/122444577-b0883200-cf6e-11eb-8097-4b4a6b048151.png)

**Comment by Devtinator** [comment]
Would like to work on this.
