### ISSUE TITLE
[FEATURE] create Other Search Info component

### ISSUE THREAD

**Issue by acharliekelly** [codeforboston/police-data-trust#52]
This component appears as Step 2 in searching for incident(s), and appears one of two ways, depending on the previous step. Type 1, you started with Search Incident(s):
![other-search-info-1](https://user-images.githubusercontent.com/46508773/122793595-63b39c80-d289-11eb-9c90-a3550f78cd5c.png)
In this case, the other search options are:
* When it occurred
* Who was involved
* What happened

Type 2, you started with Search Officer(s):
![other-search-info-2](https://user-images.githubusercontent.com/46508773/122793884-ad9c8280-d289-11eb-9611-e096804dabdb.png)
In this case, the other options are:
* When it occurred
* Where it occurred
* What happened

Either way, the component has:
* 3 search options
* Back and Next buttons to continue the search flow
* A link for "I don't know any other information", which will end the search flow

**Comment by srsexton94** [comment]
Noting: the "I don't know any other information" link should only appear if the user entered something on the dashboard landing page - if they entered the search flow without providing information, it should not display

**Comment by srsexton94** [comment]
Cancelling as per team convo 7/13
