### ISSUE TITLE
[FEATURE] create Search Who component

### ISSUE THREAD

**Issue by acharliekelly** [codeforboston/police-data-trust#55]
Search component for Who details (Department and/or Officer involved)

![search-who-comp](https://user-images.githubusercontent.com/46508773/122796891-e2f69f80-d28c-11eb-9d19-8f1b48efc4fa.png)

Component has two fields, Department and Officer. Both have dropdown auto-complete features.

**Department**
![search-who-dept](https://user-images.githubusercontent.com/46508773/122797665-b727e980-d28d-11eb-97c7-f0902644e0e4.png)

**Officer**
![search-who-officer](https://user-images.githubusercontent.com/46508773/122797719-c6a73280-d28d-11eb-9a7b-931b0a96e919.png)

Both fields have a "There was another _ involved" link, which will add a duplicate field under the first, which will behave the same way:
![search-who-others](https://user-images.githubusercontent.com/46508773/122797936-02da9300-d28e-11eb-9225-f8c8f0de0400.png)

Validation (not pictured) should require that at least one field be filled before clicking Next.
Back and Next buttons will continue the search flow.

**Comment by srsexton94** [comment]
Canceling as per conversation on 7/13 re: re-design of search flow
