### ISSUE TITLE
[FEATURE] Register basic user

### ISSUE THREAD

**Issue by acharliekelly** [codeforboston/police-data-trust#58]
### Register a Viewer (basic user)

Register viewer user
![viewer-registration](https://user-images.githubusercontent.com/46508773/122443270-69e60800-cf6d-11eb-92b2-d6ef7ea9f21f.png)

Tooltip and visible password
![viewer-registration-2](https://user-images.githubusercontent.com/46508773/122443294-70747f80-cf6d-11eb-8201-4adc13b53943.png)

Validation
![viewer-registration-validation](https://user-images.githubusercontent.com/46508773/122443357-8124f580-cf6d-11eb-9dcf-f1e5e39e08a8.png)

**Requirements**
* Six input fields
  * First Name (required)
  * Last Name (required)
  * Email Address (required, email)
  * Phone Number (required, phone)
  * Create Password (required, minimum password requirements)
  * Re-enter Password (required, match)
* Show Password
* Submit Button
* Link to Login Page
* Validation for all fields

**Comment by srsexton94** [comment]
I'd like to take this ticket

**Comment by srsexton94** [comment]
Closing after merge
