### ISSUE TITLE
[FEATURE] create Passport registration

### ISSUE THREAD

**Issue by acharliekelly** [codeforboston/police-data-trust#62]
![passport-registration](https://user-images.githubusercontent.com/46508773/122801609-5949d080-d292-11eb-8ebc-846734a2a347.png)

This is an advanced user registration, so they already have the basic Viewer account.

**Requirements**
* Refer to user's name, which should be available from profile
* Input fields:
  * Street Address (text, required)
  * City or town (text, required)
  * State (text, required)
  * Zip code (text, required)
  * Why are you signing up to the NPDC? (required, textarea, minimum character count)
* Submit button

**Validation**
![passport-registration-validation](https://user-images.githubusercontent.com/46508773/122802518-70d58900-d293-11eb-91e2-e32a64ac0dd0.png)

**Comment by dylanesque** [comment]
Could someone please assign me to this issue? Thanks!

**Comment by dylanesque** [comment]
Just out of curiosity, is there any reason the zip code should be text? This seems like something that could be confusing to a user when it gets validated.

**Comment by dylanesque** [comment]
MVP of this issue is complete, future work on this feature will be outlined as needed in subsequent tickets.
