### ISSUE TITLE
[FEATURE] create Search Where component

### ISSUE THREAD

**Issue by acharliekelly** [codeforboston/police-data-trust#63]
This is very similar to the initial Search Landing Page search, and can probably use the same component. It would only appear in the search flow if the user started with Search by Officer(s), and then later decided to add a location.

![search-where-comp](https://user-images.githubusercontent.com/46508773/122803137-37e9e400-d294-11eb-9dc4-980ea9e105f5.png)

![search-where-2](https://user-images.githubusercontent.com/46508773/122803205-4c2de100-d294-11eb-8018-39029e2df730.png)

**Requirements**
* Single input field featuring dropdown autocomplete location search
* Back & Next buttons

**Comment by srsexton94** [comment]
Canceling as per conversation on 7/13 re: re-design of search flow
