### ISSUE TITLE
[FEATURE] create Search What component

### ISSUE THREAD

**Issue by acharliekelly** [codeforboston/police-data-trust#64]
**Default View**
![search-what-comp](https://user-images.githubusercontent.com/46508773/122803514-b6468600-d294-11eb-96bc-f806ad2cca51.png)

**Tooltip**
![search-where-2](https://user-images.githubusercontent.com/46508773/122803643-dbd38f80-d294-11eb-8c29-6741e78d0f85.png)

**Requirements**
* Search field for incident summary with dropdown auto-complete
* Back & Next buttons

**Comment by srsexton94** [comment]
Cancelling as per conversation 7/13 re: re-design of search flow
