### ISSUE TITLE
[FEATURE] create Search Results page

### ISSUE THREAD

**Issue by acharliekelly** [codeforboston/police-data-trust#65]
![results-page](https://user-images.githubusercontent.com/46508773/122804032-5e5c4f00-d295-11eb-8754-6f1b842b3f24.png)

**Components**
* Map showing geographic area searched
* Search criteria
* Links to edit search (Who, What, Where, When)
* Data table with summary of incidents and link to full records

**Comment by srsexton94** [comment]
Noting for future dev: 
the results page is intended to be just a zoomed-in view of dashboard/search with the added table & search menu - not a distinct page in and of itself

Also here are the [updated wireframes](https://www.figma.com/file/TM86P6ePUar5g24pk4h6Du/NPDC-2?node-id=2%3A0)

**Comment by acharliekelly** [comment]
So maybe it would be more useful to have components for the data grid and Edit Search boxes (?)
