### ISSUE TITLE
[FEATURE] create US Map component

### ISSUE THREAD

**Issue by acharliekelly** [codeforboston/police-data-trust#66]
US Map component for multiple pages

![us-map](https://user-images.githubusercontent.com/46508773/122806211-0ecb5280-d298-11eb-8d71-20c6670e2c41.png)

**Requirements**
* Recognizable image of US
* Show data richness by state, via background color
* Show locations of data-rich cities
* Map must be usable as input control for search locations

-----------
edit 8/10/21

**NEXT STEPS**
- create a key for the map (see figma for design, use d3)
    -  include:
        color gradient block scale
        symbol guide 
    - should be able to add other types of keys and additional data
    - should be reusable for other types of visualizations (not tied to map-type)
- style markers according to the figma

**UPCOMING** / blocked
- [on hold] create pop up element (see figma) waiting for design approval + content
- [on hold] make map mobile-ready
- [on hold] interface/import files for map-data
-----------

**Comment by sashamaryl** [comment]
I'm picking this this one up thanks @acharliekelly
