### ISSUE TITLE
User-login [BUG]

### ISSUE THREAD

**Issue by acharliekelly** [codeforboston/police-data-trust#84]
Sorry, this seems too small an issue to bother writing up, but the PR is already merged, so...

In `frontend/pages/login.tsx`, line 1, the import refers to `../user-login/user-login`. But PR #83 updated the file to `../user-login/index.tsx` to conform to NextJS routing conventions, so now the login page doesn't compile. [localhost:3000/login](http://localhost:3000/login). Just need to change that one line.

**Comment by dylanesque** [comment]
This ticket should ideally trim the redundant routes: `login.tsx`/`user-login` folder and the `registration.tsx`/viewer-registration` folder are 4 different endpoints serving 2 distinct resources. I think keeping the folder versions of those files and making sure they're named what we want those particular routes to be called would be the way to go here.

**Comment by acharliekelly** [comment]
Oops, forgot to give this issue a title

**Comment by acharliekelly** [comment]
Maybe this issue should just fix the import typo, and trimming the enrollment routes should be included in #85?

**Comment by acharliekelly** [comment]
Never mind, this is incidentally fixed by #85 as well
